language: node_js
node_js:
  - "lts/carbon"
  - "stable"
sudo: false
cache:
  directories:
    - "node_modules"
script: "npm test"
#after_success:
#  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < coverage/lcov.info
