language: node_js
node_js:
  - "lts/8"
  - "stable"
sudo: false
cache:
  directories:
    - "node_modules"
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
